// <auto-generated />
namespace Desktop_TNS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migr51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migr51));
        
        string IMigrationMetadata.Id
        {
            get { return "202202060946413_migr51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
